xen-troops/linux

arch/arm64/boot/dts/renesas/Makefile
Dom0 device trees are not part of the kernel, so remove from
Makefile.
=> Remove Dom0 device trees

include/xen/interface/io/sndif.h, sound/drivers/Kconfig, sound/drivers/Makefile, sound/drivers/xen-front.c
1. Backport sndif protocol from Linux master
2. Add sound frontend
=> Add sound frontend

drivers/gpu/drm/xen/xen_drm_zcopy_drv.c
Swap incorrectly used XENMEM_populate_physmap and
XENMEM_decrease_reservation when ballonning pages in out:
use XENMEM_decrease_reservation when allocate the buffer
use XENMEM_populate_physmap when we deallocate the buffer
=> drm/xen-zcopy: Fix ballooning in/out

drivers/gpu/drm/xen/xen_drm_zcopy_drv.c, include/uapi/drm/xen_zcopy_drm.h
1. Provide wait_handle while calling
DRM_XEN_ZCOPY_DUMB_FROM_REFS IOCTL.
2. Implement IOCTL which will block until dumb buffer with
the wait handle provided be freed: this is needed for
synchronization between frontend and backend in case
frontend provides grant references of the buffer via
DRM_XEN_ZCOPY_DUMB_FROM_REFS IOCTL and which must be released before
backend replies with XENDISPL_OP_DBUF_DESTROY response.
=> drm/xen-zcopy: Implement dumb free wait IOCTL

include/linux/mmc/host.h
This clear hack is needed for RCAR boards, where SDHCI causes
problems, when it works in UHS (Ultra High Speed) mode.
Signed-off-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>
=> HACK: disable UHS mode on all MMC controlers

drivers/gpu/drm/rcar-du/rcar_du_vsp.c
Zero-out sg_tables in original plane, efectively introducing move
semantic. Seems, this fixes issue with double-free,
when rcar_du_vsp_plane_cleanup_fb() freed the same sg_table
both in original plane and in the copy.
Signed-off-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>
=> [HACK?]rcar_du_vs: zero-out sg_tables on plane duplication

include/linux/mmc/host.h
This reverts commit fd532f419548da75f3e297cd54bec8889d763870.
Seems, that this patch fixed board-specific issue, while introducing
huge performance penalties on Android guest.
=> Revert "HACK: disable UHS mode on all MMC controlers"

drivers/gpu/drm/rcar-du/rcar_du_kms.c
While running under Xen all the IOMMUs belong to
the hypervizor, thus the assumption that VSP is backed
by the IOMMU is wrong. Use CMA helper for this use-case then.
=> drm: rcar-du: Do not assume VSP has IOMMU

drivers/dma/sh/rcar-dmac.c
Due to the R-Car Gen3 HW restriction.
Please note, that this patch will decrease performance, since swiotlb bounce
buffer (for DMA transfers involving memory outside the 32-bit address space)
will be used.
=> dmaengine: rcar-dmac: Set DMA mask to 32 bits

Documentation/gpu/xen-front.rst, drivers/gpu/drm/xen/Kconfig, drivers/gpu/drm/xen/Makefile, drivers/gpu/drm/xen/xen_drm_front.c, drivers/gpu/drm/xen/xen_drm_front.h, drivers/gpu/drm/xen/xen_drm_front_gem.c, drivers/gpu/drm/xen/xen_drm_front_gem.h, drivers/gpu/drm/xen/xen_drm_front_gem_cma.c, drivers/gpu/drm/xen/xen_drm_front_shbuf.c, drivers/gpu/drm/xen/xen_drm_front_shbuf.h
This reverts commit 492aec5532879db26f19ea8a9c46f2be6ec24fe1.
=> Revert "drm/xen-front: Remove CMA support"

drivers/clk/renesas/r8a77965-cpg-mssr.c
This is follow up patch for a89a28cd7ac637baca6b6df42b361165dedc9865
=> clk:shmobile: Hide clock for SCIF2

drivers/dma/sh/rcar-dmac.c
Actually, the first patch (a39daa2) is a direct fix for the "memory corruption issue" triggered by audio record use-case (dma dev-to-mem transaction). But, it was agreed to take a few additional patches according to their descriptions. So, with these patches applied the "issue" is not observed anymore.
=> Dma fixes (copy to Gen3-test)

drivers/xen/Kconfig
The way Kconfig is written kernel doesn't enable the
Xen coordinated suspend driver when all the prerequisites
are satisfied.
Fixes: 81197697eead ("zynqmp: New platform driver for Xen coordinated suspend")
=> Fix kernel configuration for Xen coord driver

drivers/staging/android/ion/ion_system_heap.c
This HACK is needed only to comply with some internal
naming in ddk um.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>
=> HACK: Rename ion_system_heap to rcar-ion

arch/arm/xen/xt_cma_helper.c
When we assign more than 2GB memory to domain we may end up with
memory pools to be located above 32-bit address space which is
unacceptable for 32-bit devices such as VSP for example.
So, always allocate memory in 32-bit address space.
=> xt_cma_helper: Always allocate memory in 32-bit address space

arch/arm64/boot/dts/xilinx/xen-overlay.dtsi
Xen now supports new IOMMU bindings, so this leads to mix of old and new
ones, so remove the old bindings to fix that.
=> zynqmp: dts: Remove old IOMMU bindings from SMMUv2 node

arch/arm64/boot/dts/xilinx/xen-overlay.dtsi
Domain-0 doesn't need much memory and setting its size to 512 allows
easier DomU 1:1 mapping used for debugging purposes, so there is no need to
rebuild the device tree if 1:1 is needed.
=> dom0: Set Domain-0 memory to 512M

drivers/soc/renesas/rcar-sysc.c
The purpose is the same as for the following patch:
0399140 [HACK?]soc: Extend always on logic to H3 ES3.0
Some Cache IPMMUs are located in non-always-on power domains
(IPMMU-VPx, IPMMU-VCx, etc belong to A3xx domains), so mark these
domains appropriately for the system won't be able to turn them off.
=> [HACK?]soc: Extend always on logic to r8a7796 ES3.0

drivers/gpu/drm/xen/xen_drm_front.c
There are cases when pages of the display buffer are normal pages
which require cache maintenance while sharing them with the backend.
This is the case when a dumb buffer gets created with the
help of drm_gem_get_pages in Xen PV DRM driver and as the result the
final picture on the backend side is distorted with artifacts.
This can also be the case when a DMA buffer is imported from an exporter
which used allocations for the buffer which require cache maintenance
as well.
To fix that flush the relevant display buffer while sending displif's
commands for setting configuration and flipping.
[adopted for arch_dma_prep_coherent() usage]
=> drm/xen-front: flush buffer during set config and page flip

drivers/xen/balloon.c
xen_hotplug_unpopulated variable should depend from
CONFIG_XEN_BALLOON_MEMORY_HOTPLUG as long as from CONFIG_XT_CMA_HELPER.
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>
=> ballooning: Fix xen_hotplug_unpopulated visibility, depends from config

drivers/soc/renesas/rcar-sysc.c
=> soc: Extend always on logic to M3-W+ (aka M3-W ES3.0)
